<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ir.co.isc.spbp.blockchain</groupId>
        <artifactId>fabino-test</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>ir.co.isc.spbp.blockchain.fabino</groupId>
    <artifactId>fabino-unit</artifactId>
    <packaging>jar</packaging>
    <name>unit</name>

    <properties>
        <!-- ~~~~~ project lib ver ~~~~~ -->
        <version.lib.fabric.protos>0.3.7</version.lib.fabric.protos>
        <!-- ~~~~~ mvn plugins ver ~~~~~ -->
        <version.plugin.surefire>3.5.4</version.plugin.surefire>
    </properties>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.hyperledger.fabric/fabric-protos -->
        <dependency>
            <groupId>org.hyperledger.fabric</groupId>
            <artifactId>fabric-protos</artifactId>
            <version>${version.lib.fabric.protos}</version>
            <optional>true</optional>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${version.plugin.surefire}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        -Dfile.encoding=${project.build.sourceEncoding}
                        --add-opens=java.base/java.lang=ALL-UNNAMED
                        --add-opens=java.base/java.util=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>